
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php $_product = $block->getProduct(); ?>

<?php 

if ($_product->isSaleable()) {
    $buttonTitle = __('Ask a Question');
} else {
    $buttonTitle = __('Check Availability');
}

?>

<div class="box-tocart">
    <div class="fieldset">
        <div class="actions">
            <a href="#" <?= (!$_product->isSaleable()) ? "style=\"width: 55%;\"" : "" ?> 
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="primary action query"
                    >
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </a>
<!--             <?= $block->getChildHtml('', true) ?> -->
        </div>
    </div>
</div>


